version: "3.9"

services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    ports:
      - "4317:4317"   # OTLP gRPC in
      - "4318:4318"   # OTLP HTTP in
    environment:
      - SOLVIEW_ENVIRONMENT=dev
      - OTEL_SERVICE_NAMESPACE=solview
    volumes:
      - ./docker/alloy/config.river:/etc/alloy/config.river:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - tempo
      - loki
      - prometheus

  # The following services assume you have configs under ./docker/*
  # Adjust versions and paths as needed.
  prometheus:
    image: prom/prometheus:latest
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:2.9.6
    command: ["-config.file=/etc/loki/config.yml"]
    volumes:
      - ./docker/loki/loki.yml:/etc/loki/config.yml:ro
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:2.8.2
    command: ["-config.file=/etc/tempo/tempo.yml"]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo/tempo.yml:ro
    ports:
      - "3200:3200"

  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana:/etc/grafana:ro
    depends_on:
      - prometheus
      - loki
      - tempo
