[project]
name = "solview"
version = "2.1.5"
description = "Observabilidade clara como o Sol"
authors = [
    { name = "Solfácil", email = "jefferson.martins@solfacil.com.br" },
    { name = "Solfácil", email = "marcelo.souza@solfacil.com.br" },
    { name = "Solfácil", email = "vitor.garcia@solfacil.com.br" },
    { name = "Solfácil", email = "ketillin.tavares@solfacil.com.br" }
]
requires-python = ">=3.11"
readme = "README.md"
dependencies = [
    "loguru",
    "prometheus_client",
    "opentelemetry-api",
    "opentelemetry-sdk",
    "opentelemetry-instrumentation",
    "opentelemetry-exporter-otlp",
    "fastapi",
    "starlette",
    "pydantic",
    "python-dotenv",
    "orjson",
    "opentelemetry-instrumentation-fastapi>=0.53b1",
    "opentelemetry-instrumentation-httpx>=0.53b1",
    "opentelemetry-instrumentation-asyncpg>=0.53b1",
    "opentelemetry-instrumentation-logging>=0.53b1",
    "opentelemetry-instrumentation-sqlalchemy>=0.53b1",
    "asyncpg>=0.30.0",
    "sqlalchemy>=2.0.40",
    "opentelemetry-exporter-prometheus (>=0.60b1,<0.61)",
    "prometheus-fastapi-instrumentator (>=7.1.0,<8.0.0)",
    "opentelemetry-instrumentation-requests (>=0.60b1)",
    "opentelemetry-instrumentation-redis (>=0.60b1)",
    "httpx>=0.28.1",
    "redis>=7.2.1",
    "aio-pika>=9.6.2",
    "opentelemetry-instrumentation-aio-pika>=0.60b1",
]

[project.optional-dependencies]
mcp = ["fastmcp>=2.0.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = [
    "solview"
]

[tool.hatch.build.targets.wheel]
include = [
    "solview"
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "fastmcp>=2.0.0",
    "ruff>=0.15.4",
    "pytest-cov>=7.1.0",
    "ty>=0.0.25",
]
