"""
solview.metrics

Módulo universal para coleta de métricas — preparado para uso em web, workers, jobs, e APIs.
- Middleware Prometheus para ASGI (FastAPI, Starlette)
- Exporters e helpers para aplicação universal
"""

from .core import (
    METRIC_INFO,
    METRIC_REQUESTS,
    METRIC_RESPONSES,
    METRIC_REQUESTS_PROCESSING_TIME,
    METRIC_EXCEPTIONS,
    METRIC_REQUESTS_IN_PROGRESS,
)
from .exporters import (
    SolviewPrometheusMiddleware,
    prometheus_metrics_response,
)
from .custom import (
    # Kafka metrics
    KAFKA_MESSAGES_PRODUCED_TOTAL,
    KAFKA_PRODUCER_DURATION_SECONDS,
    KAFKA_PRODUCER_ERRORS_TOTAL,
    KAFKA_MESSAGES_CONSUMED_TOTAL,
    KAFKA_MESSAGE_PROCESSING_DURATION_SECONDS,
    KAFKA_CONSUMER_ERRORS_TOTAL,
    # HTTP client metrics
    HTTP_OUTGOING_REQUESTS_TOTAL,
    HTTP_OUTGOING_REQUESTS_DURATION_SECONDS,
    HTTP_OUTGOING_REQUESTS_ERRORS_TOTAL,
    HTTP_OUTGOING_REQUESTS_MEMORY_BYTES,
    # Business operations metrics
    BUSINESS_OPERATIONS_TOTAL,
    BUSINESS_OPERATIONS_DURATION_SECONDS,
    BUSINESS_OPERATIONS_MEMORY_BYTES,
)

__all__ = [
    "SolviewPrometheusMiddleware",
    "prometheus_metrics_response",
    "METRIC_INFO",
    "METRIC_REQUESTS",
    "METRIC_RESPONSES",
    "METRIC_REQUESTS_PROCESSING_TIME",
    "METRIC_EXCEPTIONS",
    "METRIC_REQUESTS_IN_PROGRESS",
    # Kafka metrics
    "KAFKA_MESSAGES_PRODUCED_TOTAL",
    "KAFKA_PRODUCER_DURATION_SECONDS",
    "KAFKA_PRODUCER_ERRORS_TOTAL",
    "KAFKA_MESSAGES_CONSUMED_TOTAL",
    "KAFKA_MESSAGE_PROCESSING_DURATION_SECONDS",
    "KAFKA_CONSUMER_ERRORS_TOTAL",
    "KAFKA_PRODUCER_MEMORY_BYTES",
    "KAFKA_CONSUMER_MEMORY_BYTES",
    # HTTP client metrics
    "HTTP_OUTGOING_REQUESTS_TOTAL",
    "HTTP_OUTGOING_REQUESTS_DURATION_SECONDS",
    "HTTP_OUTGOING_REQUESTS_ERRORS_TOTAL",
    "HTTP_OUTGOING_REQUESTS_MEMORY_BYTES",
    # Business operations metrics
    "BUSINESS_OPERATIONS_TOTAL",
    "BUSINESS_OPERATIONS_DURATION_SECONDS",
    "BUSINESS_OPERATIONS_MEMORY_BYTES",
]